package main

import (
	"compress/flate"
	"io"
	"net/http"
	"os"
	"time"

	"github.com/epkgs/blink"
	"github.com/epkgs/blink/pkg/alert"
	"github.com/epkgs/blink/pkg/downloader"
)

func main() {
	app := blink.NewApp()
	defer app.Exit()

	view := app.CreateWebWindowPopup(blink.WithWebWindowSize(1200, 900))
	view.Window.SetTitle("下载测试")
	view.Window.MoveToCenter()

	view.OnDestroy(func() {
		os.Exit(0)
	})

	// 直接下载
	_, _ = app.Download("https://httpbin.org/robots.txt")

	// deflate压缩内容下载
	_, _ = app.Download("https://comment.bilibili.com/177987845.xml", func(o *downloader.Option) {
		o.Interceptors.HttpDownloading = func(resp *http.Response, req *http.Request) io.Reader {
			// 检查Content-Encoding是否为deflate
			contentEncoding := resp.Header.Get("Content-Encoding")
			if contentEncoding == "deflate" {
				// 如果是deflate编码，解压缩数据
				return flate.NewReader(resp.Body)
			} else {
				// 如果不是deflate编码，直接将响应体内容写入文件
				return resp.Body
			}
		}
	})

	// 保存文件之前修改文件名
	app.Download("https://httpbin.org/image", func(o *downloader.Option) {
		o.Interceptors.BeforeSaveFile = func(job *downloader.Job) {
			// 修改文件名
			job.FileName += ".png"
		}
	})

	view.LoadURL("https://catalog.ldc.upenn.edu/login")
	view.ShowWindow()
	/*
		用户名: duyu20@mails.tsinghua.edu.cn
		密码: algebra-2023
		右侧有个Downloads连接：https://catalog.ldc.upenn.edu/organization/downloads
	*/
	/*
		miniblink的cookie.dat：
			# Netscape HTTP Cookie File
			# https://curl.haxx.se/docs/http-cookies.html
			# This file was generated by libcurl! Edit at your own risk.

			.upenn.edu	TRUE	/	FALSE	1723686255	_gat	1
			#HttpOnly_.ldc.upenn.edu	TRUE	/	TRUE	0	_xiexie	d425bbf084773bbb8e957b209a603a2a
			.upenn.edu	TRUE	/	FALSE	1786758196	_ga_J9ZV05KG56	GS1.2.1723685408.1.1.1723686196.0.0.0
			.upenn.edu	TRUE	/	FALSE	1723772595	_gid	GA1.2.1524576267.1723685407
			.upenn.edu	TRUE	/	FALSE	1786758195	_ga	GA1.2.1710216791.1723685407
			catalog.ldc.upenn.edu	FALSE	/	TRUE	2354837398	guest_token	BAhJIig1bmVjdW9ObnVzaHFpOE13SFBvY0lRMTcyMzY4NTM5ODY1NQY6BkVU--a8ea7a3c1feb345f279e3a0baccb74a02a835b5c
			#HttpOnly_catalog.ldc.upenn.edu	FALSE	/	TRUE	2354837398	token	BAhJIig1bmVjdW9ObnVzaHFpOE13SFBvY0lRMTcyMzY4NTM5ODY1NQY6BkVU--a8ea7a3c1feb345f279e3a0baccb74a02a835b5c
			#HttpOnly_.ldc.upenn.edu	TRUE	/	TRUE	1724895634	remember_spree_user_token	BAhbCFsGaQOYjgFJIhk1V0NGeVpSQ3pnZ1JlWXV5bTZmdQY6BkVUSSIWMTcyMzY4NjAzNC4xNDEyNDMGOwBG--e3c3ddcae8444aae4c86c79a420c8188177ddb8f
	*/
	// 验证Cookies并重定向下载
	view.OnDownload(func(url string) {

		_, err := app.Download(url, func(o *downloader.Option) {
			o.Cookies, _ = app.GetCookies()
			o.InsecureSkipVerify = true
			o.Timeout = 10 * time.Minute

			// 可自定义其他下载选项

		})

		if err != nil {
			alert.Error("下载失败", err.Error())
			return
		}

		alert.Info("提示", "下载成功！")
	})

	app.KeepRunning()

}
